module.exports = {
  apps: [
    {
      name: "dappscore-frontend",
      script: "node_modules/.bin/next",
      args: "start",
      cwd: "/var/www/dappscore/dappscore",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      instances: "max",
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      merge_logs: true,
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "dappscore-backend",
      script: "dist/index.js",
      cwd: "/var/www/dappscore/dappscore/functions",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      merge_logs: true,
    },
  ],
};
